FROM golang:latest

# env
ENV ZOOKEEPER_HOST 10.0.0.38
ENV ZOOKEEPER_PORT 22181
ENV TOPIC email_topic

##Create /app directory
RUN mkdir /app


#copy go mod and sum files
WORKDIR /app
COPY go.mod .
RUN go mod download 
COPY . .

# copy app
# ADD . /app
# WORKDIR /app

# COPY get.sh /app
# RUN bash get.sh

#Download dependencies

# RUN go mod download 

# build
RUN go build -o app .
# RUN bin bash pwd
CMD ["./app"]
# ENTRYPOINT ["/app/docker-entrypoint.sh"]